### ISSUE TITLE
Iteration 1 - errors in 3 tests

### ISSUE THREAD

**Issue by jbrucker** [PanitanPlengkham/ku-polls#18]
Using the code I pulled after end of Iteration 1, 3 tests fail:

======================================================================
FAIL: test_future_question_and_past_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Panitan/ku-polls/mysite/polls/tests.py", line 93, in test_future_question_and_past_question
    ['<Question: Past question.>']
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 1072, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Question: Question object (1)>'] != ['<Question: Past question.>']

First differing element 0:
'<Question: Question object (1)>'
'<Question: Past question.>'

- ['<Question: Question object (1)>']
+ ['<Question: Past question.>']

======================================================================
FAIL: test_past_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Panitan/ku-polls/mysite/polls/tests.py", line 70, in test_past_question
    ['<Question: Past question.>']
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 1072, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Question: Question object (1)>'] != ['<Question: Past question.>']

First differing element 0:
'<Question: Question object (1)>'
'<Question: Past question.>'

- ['<Question: Question object (1)>']
+ ['<Question: Past question.>']

======================================================================
FAIL: test_two_past_questions (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Panitan/ku-polls/mysite/polls/tests.py", line 105, in test_two_past_questions
    ['<Question: Past question 2.>', '<Question: Past question 1.>']
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 1072, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Question: Question object (2)>', '<Question: Question object (1)>'] != ['<Question: Past question 2.>', '<Question: Past question 1.>']

First differing element 0:
'<Question: Question object (2)>'
'<Question: Past question 2.>'

- ['<Question: Question object (2)>', '<Question: Question object (1)>']
+ ['<Question: Past question 2.>', '<Question: Past question 1.>']

----------------------------------------------------------------------
Ran 10 tests in 0.057s

FAILED (failures=3)

**Comment by PanitanPlengkham** [comment]
Problem is solved. It's because I forgot to create __str__ for Question model.
